### ISSUE TITLE
Allow a max result limit to be set

### ISSUE THREAD

**Issue by Billy-Sheppard** [esheppa/eigenlog#1]
Allow a maximum limit to be set on returning rows, which once hit the function will stop filtering and return the dataset. 

This will allow for wide range filters without causing a request to return millions of rows.

For example having a limit set at 10,000, and using a super wide date filter, after the limit is hit, the requested rows truncated to a length of 10,000.

**Comment by esheppa** [comment]
I've now added this as a field in `QueryParams` in #2
